# Generated by Django 2.0.1 on 2018-02-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250)),
                ('slug', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
